import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import {useEffect} from "react";
import {useRouter} from 'next/router';
import {getUserStartStatus} from "../../components/dbUtils";


const Home: NextPage = () => {
    const router = useRouter()
    const userRFID = router.query.id as string

    useEffect(() => {
        (async () => {
            const state = await getUserStartStatus(userRFID)
            // console.log(state)
        })()


    }, [])
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>

            </main>
        </div>
    )
}

export default Home
